# Generated by Django 5.2.15 on 2026-06-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('poster_image_url', models.URLField(blank=True, max_length=500)),
                ('banner_image_url', models.URLField(blank=True, max_length=500)),
                ('type', models.CharField(blank=True, choices=[('TVA', 'TVA'), ('MOVIE', 'Movie'), ('OVA', 'OVA')], max_length=30)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming')], default='ONGOING', max_length=30)),
                ('studio', models.CharField(blank=True, max_length=100)),
                ('synopsis', models.TextField(blank=True)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('banner_image_url', models.URLField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('illustrator', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=30)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MetadataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('GENRE', 'Genre'), ('TAG', 'Tag'), ('STUDIO', 'Studio')], max_length=20)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnimeMangaMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_season_label', models.CharField(blank=True, max_length=50)),
                ('anime_episode_from', models.PositiveIntegerField(blank=True, null=True)),
                ('anime_episode_to', models.PositiveIntegerField(blank=True, null=True)),
                ('manga_volume_from', models.PositiveIntegerField(blank=True, null=True)),
                ('manga_volume_to', models.PositiveIntegerField(blank=True, null=True)),
                ('manga_chapter_from', models.PositiveIntegerField(blank=True, null=True)),
                ('manga_chapter_to', models.PositiveIntegerField(blank=True, null=True)),
                ('continue_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('continue_chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('mapping_text', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=500)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_mappings', to='works.anime')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_mappings', to='works.manga')),
            ],
            options={
                'ordering': ['anime_id', 'anime_episode_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MangaEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='works.manga')),
            ],
            options={
                'ordering': ['volume_number', 'chapter_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.manga')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.metadatatag')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mangas', through='works.MangaTag', to='works.metadatatag'),
        ),
        migrations.CreateModel(
            name='AnimeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.anime')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.metadatatag')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='animes', through='works.AnimeTag', to='works.metadatatag'),
        ),
        migrations.AddConstraint(
            model_name='mangatag',
            constraint=models.UniqueConstraint(fields=('manga', 'tag'), name='unique_manga_tag'),
        ),
        migrations.AddConstraint(
            model_name='animetag',
            constraint=models.UniqueConstraint(fields=('anime', 'tag'), name='unique_anime_tag'),
        ),
    ]
